Repository spiral/testing, pull requests merged in 2023-04, with the labels that each got.

#45 Up phpunit version
  .github/workflows/phpunit.yml
  .github/workflows/run-tests.yml
  composer.json
  phpunit.xml
  src/Session/FakeSessionSection.php
  tests/src/ConsoleTest.php
  tests/src/Core/BootloaderTest.php
  tests/src/Event/EventDispatcherTest.php
  tests/src/Http/FakeHttpTest.php
Labels: enhancement

#48 Fixes acceptable types for queue payload
  .github/workflows/phpunit.yml
  composer.json
  src/Queue/FakeQueue.php
Labels: bug, enhancement

#51 Fixes problem with returning value using FakeEventDispatcher::dispatch method, when application doesn't have Event bus implementation
  .gitignore
  src/Events/FakeEventDispatcher.php
  tests/src/Event/EventDispatcherTest.php
Labels: bug

#52 Adds backward compatibility with phpunit 9.x
  composer.json
Labels: bug
